// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzb40_CXeoRWsz-0LXI80Q3fKA400cWag',
    appId: '1:78048559706:web:9c6fb55dce363fc28bce63',
    messagingSenderId: '78048559706',
    projectId: 'quizgeo-46521',
    authDomain: 'quizgeo-46521.firebaseapp.com',
    databaseURL: 'https://quizgeo-46521-default-rtdb.firebaseio.com',
    storageBucket: 'quizgeo-46521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2iZFmNDEhfZKyqM-V7G6erbNk89V9sI',
    appId: '1:78048559706:android:510f9c2f7e65e5d38bce63',
    messagingSenderId: '78048559706',
    projectId: 'quizgeo-46521',
    databaseURL: 'https://quizgeo-46521-default-rtdb.firebaseio.com',
    storageBucket: 'quizgeo-46521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArukl9hXSlFr7G5o_cKNqKNVChPFoLcjc',
    appId: '1:78048559706:ios:ab4eeb54b356b6e58bce63',
    messagingSenderId: '78048559706',
    projectId: 'quizgeo-46521',
    databaseURL: 'https://quizgeo-46521-default-rtdb.firebaseio.com',
    storageBucket: 'quizgeo-46521.appspot.com',
    iosClientId: '78048559706-c1giu4m60moq7qf13j2nj6njgbfqsi27.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArukl9hXSlFr7G5o_cKNqKNVChPFoLcjc',
    appId: '1:78048559706:ios:ab4eeb54b356b6e58bce63',
    messagingSenderId: '78048559706',
    projectId: 'quizgeo-46521',
    databaseURL: 'https://quizgeo-46521-default-rtdb.firebaseio.com',
    storageBucket: 'quizgeo-46521.appspot.com',
    iosClientId: '78048559706-c1giu4m60moq7qf13j2nj6njgbfqsi27.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
